import Container from "@/components/Container";
import Main from "@/components/Main/Main";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>Про нас | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <></>
        </Container>
      </Main>
    </>
  );
};

export default About;
