import Container from "@/components/Container";
import Main from "@/components/Main/Main";
import { URL } from "@/data";
import { Post } from "@/ts/types/app_types";
import axios from "axios";

import Head from "next/head";
import { useEffect, useState } from "react";
import PostTableRow from "./PostTableRow";

const AdminDashboard = () => {
  const [postsData, setPostsData] = useState<{
    posts: Post[];
    total: number;
    page: number;
  } | null>(null);

  const fetchPosts = async () => {
    try {
      const response = await axios.get(`${URL}/posts`);
      setPostsData(response.data);
    } catch (e) {
      console.log(e);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  if (!postsData) return <></>;

  return (
    <>
      <Head>
        <title>Admin Dashboard | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div className="flex flex-col flex-1 py-[30px]">
          <div className="flex flex-col flex-1 px-[25px]">
            <div className="mb-[15px] font-[500] bg-white px-[15px] py-[20px] rounded-[8px]">
              Кількість постів: {postsData.total}
            </div>
            <table className="min-w-full divide-y divide-gray-200 bg-white rounded-[8px] overflow-hidden">
              <thead className="bg-black">
                <tr>
                  <th
                    scope="col"
                    className="flex items-center px-6 py-3 text-xs font-bold text-left text-gray-300 uppercase "
                  >
                    ID
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-xs font-bold text-left text-gray-300 uppercase "
                  >
                    Дата
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-xs font-bold text-left text-gray-300 uppercase "
                  >
                    Фото
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-xs font-bold text-left text-gray-300 uppercase "
                  >
                    Заголовок
                  </th>
                  <th
                    scope="col"
                    className="px-6 py-3 text-xs font-bold text-right text-gray-300 uppercase "
                  >
                    Переглядів
                  </th>
                  <th
                    scope="col"
                    className="px-[60px] py-3 text-xs font-bold text-right text-gray-300 uppercase "
                  ></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {postsData.posts.map((post) => {
                  return <PostTableRow key={post._id} data={post} />;
                })}
              </tbody>
            </table>
          </div>
        </div>
      </Main>
    </>
  );
};

export default AdminDashboard;
