import Container from "@/components/Container";
import { Post as PostType } from "@/ts/types/app_types";

import { URL } from "../data";

import Main from "@/components/Main/Main";
import Head from "next/head";
import uuid from "react-uuid";

import Post from "@/components/Posts/Post";
import axios from "axios";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";
import animation from "../styles/modules/animations.module.css";
import NoContentError from "@/components/Errors/NoContentError";

type LatestNewsPropsType = {
  posts: PostType[] | null;
};

const LatestNews = (props: LatestNewsPropsType) => {
  const { posts } = props;
  return (
    <>
      <div className="flex flex-col flex-1 gap-[15px] max-w-[800px] w-full">
        <div className="px-[10px] text-[32px] font-[600]">
          <h1>Останні новини</h1>
        </div>
        {!posts && <NoContentError />}
        {posts && (
          <div className="flex flex-col gap-[15px]">
            {posts.map((post: PostType) => {
              return <Post key={uuid()} data={post} />;
            })}
          </div>
        )}
        <div className="flex justify-end">
          <Link href={"/news"}>
            <button
              className={`flex items-center gap-[10px] font-[500] border px-[20px] py-[10px] rounded-[8px] text-[16px] bg-neutral-800 transition-bg duration-200 text-[#fff] ${animation["arrow-right-animation"]}`}
            >
              Усі новини
              <FontAwesomeIcon
                className={`w-[12px] mt-[4px] icon`}
                icon={faArrowRight}
              />
            </button>
          </Link>
        </div>
      </div>
    </>
  );
};

type HomePageProps = {
  posts: PostType[] | null;
};

const Home = (props: HomePageProps) => {
  const { posts } = props;
  return (
    <>
      <Head>
        <title>Головна | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <div className="flex flex-col flex-1 py-[30px]">
            <div className="flex gap-[30px] px-[25px] flex-1">
              <LatestNews posts={posts} />
            </div>
          </div>
        </Container>
      </Main>
    </>
  );
};

export async function getServerSideProps() {
  let posts = null;
  try {
    posts = await axios
      .get("/post?limit=5&sortDate=desc")
      .then((res) => res.data.posts);
  } catch (e) {
    console.log(e);
  }

  return {
    props: {
      posts,
    },
  };
}

export default Home;
