import Container from "@/components/Container";
import DeanCard from "@/components/DeanCard";
import DepartmentsList from "@/components/DepartmentsList";
import Main from "@/components/Main/Main";
import Head from "next/head";

import mizaImage from "../../../assets/images/people/miza.jpg";

const AboutBlock = () => {
  return (
    <>
      <div className="flex flex-col max-w-[750px] rounded-[8px] bg-white pt-[24px] px-[30px] pb-[30px]">
        <div className="px-[10px] text-[32px] font-[600]">
          <h1 className="text-center">
            КАФЕДРА ІНФОРМАЦІЙНИХ УПРАВЛЯЮЧИХ СИСТЕМ ТА ТЕХНОЛОГІЙ
          </h1>
        </div>
        <div className="mt-[25px]">
          <p className="leading-[24px] indent-10 mb-[15px]">
            Кафедра інформаційних управляючих систем та технологій була створена
            в 2000 р. шляхом поділу кафедри інформатики та інформаційних
            технологій на дві кафедри: інформаційних управляючих систем та
            технологій і загальної інформатики та математичного моделювання.
            Першим завідувачем кафедри був д.т.н., проф. Василенко Ю.А.
          </p>
          <p className="leading-[24px] indent-10">
            Кафедра є випусковою і здійснює підготовку фахівців-програмістів за
            спеціальністю 122 «Комп’ютерні науки» (бакалавр, магістр та доктор
            філософії). Випускники кафедри інформаційних управляючих систем та
            технологій здобувають кваліфікацію «Фахівець з розробки комп’ютерних
            програм».
          </p>
        </div>
      </div>
    </>
  );
};

const ItTechnology = () => {
  return (
    <>
      <Head>
        <title>It-technology | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <div className="flex flex-col flex-1 py-[30px]">
            <div className="flex gap-[30px] px-[25px] flex-1">
              <AboutBlock />
              <div className="flex flex-col h-fit sticky top-[30px] min-w-[350px]">
                <DeanCard
                  image={{ url: mizaImage, className: "max-w-[243px]" }}
                  title="Завідувач кафедри:"
                  fullname="Міца Олександр Володимирович"
                  description="доктор технічних наук, професор"
                />
                <DepartmentsList className="mt-[30px]" />
              </div>
            </div>
          </div>
        </Container>
      </Main>
    </>
  );
};

export default ItTechnology;
