import Container from "@/components/Container";
import Main from "@/components/Main/Main";
import Head from "next/head";
import { useSelector } from "react-redux";
import { Category } from "@/ts/types/app_types";
import { Post as PostType } from "@/ts/types/app_types";
import Post from "@/components/Posts/Post";
import useFetchData from "@/custom-hooks/useFetchData";
import uuid from "react-uuid";
import { URL } from "@/data";

import NewsFilter from "@/components/News/NewsFilter";
import { useRouter } from "next/router";
import { useEffect } from "react";

const NewsPage = () => {
  const { asPath } = useRouter();

  const createFetchStr = (basicURL: string, asPath: string) => {
    return `${basicURL}${
      asPath.split("?")[1] ? `?${asPath.split("?")[1]}&limit=10` : "?limit=10"
    }`;
  };

  const { data: posts, setURL } = useFetchData(
    createFetchStr(`${URL}/posts`, asPath)
  );

  useEffect(() => {
    setURL(createFetchStr(`${URL}/posts`, asPath));
  }, [asPath]);

  return (
    <>
      <Head>
        <title>Новини | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <div className="flex flex-col flex-1 py-[30px]">
            <div className="flex flex-col flex-1 px-[25px]">
              <div className="flex flex-col gap-[15px] max-w-[800px] w-full">
                <NewsFilter />
                {posts && (
                  <>
                    <div className="flex flex-col gap-[15px]">
                      {posts.map((post: PostType) => {
                        return <Post key={uuid()} data={post} />;
                      })}
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        </Container>
      </Main>
    </>
  );
};

export default NewsPage;
