import Container from "@/components/Container";
import Main from "@/components/Main/Main";
import Head from "next/head";
import { useSelector } from "react-redux";
import { Category } from "@/ts/types/app_types";
import { Post as PostType } from "@/ts/types/app_types";
import Post from "@/components/Posts/Post";
import useFetchData from "@/custom-hooks/useFetchData";
import uuid from "react-uuid";
import { PAGE_URL, URL } from "@/data";

import NewsFilter from "@/components/News/NewsFilter";
import { useRouter } from "next/router";
import { useEffect, useMemo, useRef, useState } from "react";
import Pagination from "@/components/Pagination/Pagination";
import { genArrWithElement, queryToUrl, urlToQuery } from "@/helpers";
import SkeletonPost from "@/components/Posts/SkeletonPost";
import { useQuery } from "react-query";
import axios from "axios";

const NewsPage = () => {
  const isFirstRender = useRef(true);
  const limit = 10;
  const { asPath, push } = useRouter();

  const query = useMemo(() => {
    return urlToQuery(asPath);
  }, []);

  const [filter, setFilter] = useState<NewsFilter>({
    category: query.category ? query.category : [],
    title: query.title ? query.title[0] : "",
    page: query.page ? Number(query.page[0]) : 1,
  });

  const queryUrl = useMemo(() => {
    return queryToUrl(filter);
  }, [filter]);

  const fetchPosts = async () => {
    const data = await axios
      .get(`/posts?limit=10&${queryToUrl(filter)}`)
      .then((res) => res.data);
    return data;
  };

  const { data, isLoading, isError } = useQuery(
    ["fetch-posts", filter],
    fetchPosts
  );

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }
    push(
      `${PAGE_URL}/news${queryUrl.length != 0 ? `?${queryUrl}` : ""}`,
      undefined,
      { shallow: true }
    );
  }, [filter]);

  return (
    <>
      <Head>
        <title>Новини | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <div className="flex flex-col flex-1 py-[30px]">
            <div className="flex flex-col flex-1 px-[25px]">
              <div className="flex flex-col flex-1 gap-[15px] max-w-[800px] w-full">
                <NewsFilter filter={filter} setFilter={setFilter} />
                {isLoading && <>{genArrWithElement(10, <SkeletonPost />)}</>}
                {data && (
                  <>
                    <div className="flex flex-col flex-1 gap-[15px]">
                      {data.posts.map((post: PostType) => {
                        return <Post key={uuid()} data={post} />;
                      })}
                    </div>
                  </>
                )}
                {data && (
                  <Pagination
                    total={data.total}
                    currentPage={data.page}
                    limit={limit}
                    setFilter={setFilter}
                  />
                )}
              </div>
            </div>
          </div>
        </Container>
      </Main>
    </>
  );
};

export default NewsPage;
