import Container from "@/components/Container";
import Main from "@/components/Main/Main";
import Head from "next/head";

const Software = () => {
  return (
    <>
      <Head>
        <title>Software | UZHNU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <div className="flex flex-col flex-1 py-[30px]">
            <div className="flex gap-[30px] px-[25px] flex-1"></div>
          </div>
        </Container>
      </Main>
    </>
  );
};

export default Software;
